[workspace]
resolver = "2"

members = [ 
  "projects/branches",
]

exclude = [
  "projects/hello_world",
  "projects/hello_cargo",
  "projects/guessing_game",
  "projects/chapter_3",
  "projects/full_month",
  "projects/no_type_annotations",
  "projects/variables",
]
